language: node_js
node_js:
  - '12'
install:
  - npm install
script:
  - npm run build
  - npm run build:web
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: ./dist/
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
