language: node_js
dist: xenial
os: linux
node_js:
  - '12'
install:
  - npm install
script:
  - npm run build
  - npm run build:web
deploy:
  strategy: git
  provider: pages
  cleanup: false
  local_dir: ./dist/
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
